#!/usr/bin/env python3
"""
RecipePool - Recipe Pool Manager (Layer 3)

Responsible for managing Mutation Recipes generated by PathFinder, providing:
1. Recipe addition and retirement
2. Selection based on priority and success rate
3. Recipe statistics and evaluation
4. Recipe persistence

Architecture: DETAILED_ARCHITECTURE.md Line 260-290
"""

import json
import time
from pathlib import Path
from typing import List, Dict, Optional, Any
from dataclasses import dataclass, field


@dataclass
class RecipeStats:
    """Recipe statistics"""
    attempt_count: int = 0
    success_count: int = 0
    new_coverage_count: int = 0
    last_success_time: float = 0.0

    @property
    def success_rate(self) -> float:
        """Success rate"""
        if self.attempt_count == 0:
            return 0.0
        return self.success_count / self.attempt_count

    def to_dict(self) -> Dict:
        """Convert to dictionary"""
        return {
            'attempt_count': self.attempt_count,
            'success_count': self.success_count,
            'new_coverage_count': self.new_coverage_count,
            'success_rate': self.success_rate,
            'last_success_time': self.last_success_time
        }


class RecipePool:
    """
    Recipe Pool Manager (Layer 3: Optimization)

    Manages mutation recipes generated by PathFinder, implementing intelligent
    selection and retirement strategies.

    Architecture: DETAILED_ARCHITECTURE.md Line 260-290
    """

    def __init__(self, max_active: int = 50, retirement_threshold: int = 100):
        """
        Initialize RecipePool

        Args:
            max_active: Maximum number of active recipes
            retirement_threshold: Retirement threshold (number of attempts)
        """
        # Recipe storage
        self.active_recipes: List[Dict] = []  # Active recipes
        self.retired_recipes: List[Dict] = []  # Retired recipes

        # Recipe index (syscall_name -> recipes)
        self.recipe_index: Dict[str, List[Dict]] = {}

        # Recipe statistics
        self.stats: Dict[str, RecipeStats] = {}

        # Configuration
        self.max_active = max_active
        self.retirement_threshold = retirement_threshold

        # Global statistics
        self.total_added = 0
        self.total_retired = 0
        
        print(f"[RecipePool] Initialized (max_active={max_active}, "
              f"retirement_threshold={retirement_threshold})")
    
    def add_recipes(self, recipes: List[Dict]):
        """
        Add recipes to the pool

        Args:
            recipes: List of recipe dictionaries (from PathFinder)
        """
        for recipe in recipes:
            recipe_id = recipe.get('id', len(self.active_recipes))
            recipe['id'] = recipe_id

            # Add to active pool
            self.active_recipes.append(recipe)
            self.total_added += 1

            # Build index
            syscall_name = recipe.get('syscall_name', '')
            if syscall_name:
                if syscall_name not in self.recipe_index:
                    self.recipe_index[syscall_name] = []
                self.recipe_index[syscall_name].append(recipe)

            # Initialize statistics
            if recipe_id not in self.stats:
                self.stats[recipe_id] = RecipeStats()

        print(f"[RecipePool] Added {len(recipes)} recipes "
              f"(total active: {len(self.active_recipes)})")

        # Check if pruning is needed
        if len(self.active_recipes) > self.max_active:
            self._prune_recipes()
    
    def get_recipe_for_trace(self, trace: Any) -> Optional[Dict]:
        """
        Select the best recipe for a given trace

        Args:
            trace: Trace object (containing syscalls information)

        Returns:
            Recipe dictionary or None

        Architecture: DETAILED_ARCHITECTURE.md Line 269-280
        """
        if not self.active_recipes:
            return None

        # Method 1: Match based on syscalls in the trace
        matching_recipes = []

        # Assume trace has a syscalls attribute
        if hasattr(trace, 'syscalls'):
            for recipe in self.active_recipes:
                syscall_idx = recipe.get('syscall_index', -1)
                if 0 <= syscall_idx < len(trace.syscalls):
                    # Recipe is applicable to this trace
                    matching_recipes.append(recipe)
        else:
            # If trace has no detailed info, return all recipes
            matching_recipes = self.active_recipes

        if not matching_recipes:
            return None

        # Method 2: Sort by priority and attempt count
        sorted_recipes = sorted(
            matching_recipes,
            key=lambda r: (
                r.get('priority', 5),  # Higher priority first
                -self.stats[r['id']].attempt_count  # Fewer attempts first
            ),
            reverse=True
        )

        return sorted_recipes[0]
    
    def update_recipe_result(
        self,
        recipe: Dict,
        success: bool,
        new_coverage: int = 0
    ):
        """
        Update recipe execution result

        Args:
            recipe: Recipe dictionary
            success: Whether successful (new coverage found)
            new_coverage: Number of newly discovered coverage entries

        Architecture: DETAILED_ARCHITECTURE.md Line 282-289
        """
        recipe_id = recipe['id']

        if recipe_id not in self.stats:
            self.stats[recipe_id] = RecipeStats()

        stat = self.stats[recipe_id]
        stat.attempt_count += 1

        if success:
            stat.success_count += 1
            stat.new_coverage_count += new_coverage
            stat.last_success_time = time.time()

        # Check if recipe should be retired
        if stat.attempt_count >= self.retirement_threshold:
            if stat.success_rate < 0.1:  # Success rate < 10%
                self._retire_recipe(recipe)
    
    def _retire_recipe(self, recipe: Dict):
        """Retire a recipe"""
        recipe_id = recipe['id']

        # Remove from active pool
        self.active_recipes = [r for r in self.active_recipes if r['id'] != recipe_id]

        # Add to retired pool
        self.retired_recipes.append(recipe)
        self.total_retired += 1

        # Update index
        syscall_name = recipe.get('syscall_name', '')
        if syscall_name in self.recipe_index:
            self.recipe_index[syscall_name] = [
                r for r in self.recipe_index[syscall_name] if r['id'] != recipe_id
            ]
        
        print(f"[RecipePool] Retired recipe {recipe_id} "
              f"(attempts={self.stats[recipe_id].attempt_count}, "
              f"success_rate={self.stats[recipe_id].success_rate:.1%})")
    
    def _prune_recipes(self):
        """Prune recipe pool (keep high-quality ones)"""
        if len(self.active_recipes) <= self.max_active:
            return

        # Sort by success rate and priority
        sorted_recipes = sorted(
            self.active_recipes,
            key=lambda r: (
                self.stats[r['id']].success_rate,
                r.get('priority', 5),
                self.stats[r['id']].new_coverage_count
            ),
            reverse=True
        )

        # Keep top N
        to_keep = sorted_recipes[:self.max_active]
        to_retire = sorted_recipes[self.max_active:]
        
        for recipe in to_retire:
            self._retire_recipe(recipe)
        
        print(f"[RecipePool] Pruned {len(to_retire)} recipes "
              f"(active: {len(self.active_recipes)})")
    
    def get_statistics(self) -> Dict:
        """Get RecipePool statistics"""
        active_stats = [self.stats[r['id']] for r in self.active_recipes]
        
        return {
            'total_added': self.total_added,
            'active_recipes': len(self.active_recipes),
            'retired_recipes': len(self.retired_recipes),
            'total_retired': self.total_retired,
            'avg_success_rate': (
                sum(s.success_rate for s in active_stats) / len(active_stats)
                if active_stats else 0.0
            ),
            'total_attempts': sum(s.attempt_count for s in active_stats),
            'total_successes': sum(s.success_count for s in active_stats),
        }
    
    def save_to_file(self, output_path: Path):
        """Save RecipePool to file"""
        data = {
            'active_recipes': self.active_recipes,
            'retired_recipes': self.retired_recipes,
            'stats': {
                str(recipe_id): stat.to_dict() 
                for recipe_id, stat in self.stats.items()
            },
            'metadata': {
                'total_added': self.total_added,
                'total_retired': self.total_retired,
                'timestamp': time.time()
            }
        }
        
        with open(output_path, 'w') as f:
            json.dump(data, f, indent=2)
        
        print(f"[RecipePool] Saved to {output_path}")
    
    def load_from_file(self, input_path: Path):
        """Load RecipePool from file"""
        with open(input_path, 'r') as f:
            data = json.load(f)

        self.active_recipes = data.get('active_recipes', [])
        self.retired_recipes = data.get('retired_recipes', [])

        # Restore statistics
        stats_data = data.get('stats', {})
        for recipe_id_str, stat_dict in stats_data.items():
            recipe_id = int(recipe_id_str)
            self.stats[recipe_id] = RecipeStats(**stat_dict)

        # Rebuild index
        self.recipe_index.clear()
        for recipe in self.active_recipes:
            syscall_name = recipe.get('syscall_name', '')
            if syscall_name:
                if syscall_name not in self.recipe_index:
                    self.recipe_index[syscall_name] = []
                self.recipe_index[syscall_name].append(recipe)
        
        metadata = data.get('metadata', {})
        self.total_added = metadata.get('total_added', len(self.active_recipes))
        self.total_retired = metadata.get('total_retired', len(self.retired_recipes))
        
        print(f"[RecipePool] Loaded from {input_path} "
              f"({len(self.active_recipes)} active recipes)")
    
    def print_summary(self):
        """Print RecipePool summary"""
        stats = self.get_statistics()
        
        print("\n" + "=" * 60)
        print("RecipePool Summary")
        print("=" * 60)
        print(f"  Active recipes:     {stats['active_recipes']}")
        print(f"  Retired recipes:    {stats['retired_recipes']}")
        print(f"  Total added:        {stats['total_added']}")
        print(f"  Total attempts:     {stats['total_attempts']}")
        print(f"  Total successes:    {stats['total_successes']}")
        print(f"  Avg success rate:   {stats['avg_success_rate']:.1%}")
        print("=" * 60 + "\n")


def test_recipe_pool():
    """Test RecipePool"""
    print("Testing RecipePool...")

    # Create pool
    pool = RecipePool(max_active=10)

    # Add test recipes
    test_recipes = [
        {
            'id': i,
            'source_branch': f'0x{1000+i:x}',
            'target_branch': f'0x{2000+i:x}',
            'syscall_name': 'read' if i % 2 == 0 else 'write',
            'syscall_index': i,
            'priority': 5 + (i % 3),
            'mutation_type': 'FUZZ_CMD_MUTATE_ARG',
        }
        for i in range(15)
    ]
    
    pool.add_recipes(test_recipes)

    # Simulate usage
    class MockTrace:
        def __init__(self):
            self.syscalls = [None] * 20

    trace = MockTrace()

    for _ in range(50):
        recipe = pool.get_recipe_for_trace(trace)
        if recipe:
            # Simulate execution result
            import random
            success = random.random() < 0.3
            new_cov = random.randint(0, 5) if success else 0
            pool.update_recipe_result(recipe, success, new_cov)
    
    # 打印摘要
    pool.print_summary()
    
    print("✅ RecipePool test passed")


if __name__ == '__main__':
    test_recipe_pool()

