[ftpconfig]
port=2121
maxusers=2
interface=127.0.0.1
external_ip=127.0.0.1
local_mask=255.255.255.0
minport=40000
maxport=40100
logfilepath=/tmp/rrfuzz_lightftp.log
CATrustFile=/etc/ssl/certs/ca-certificates.crt
ServerCertificate=/tmp/rrfuzz_lightftp.crt
Keyfile=/tmp/rrfuzz_lightftp.key
KeyfilePassword=
goodbyemsg=Goodbye!
keepalive=0
follow_symlinks=0

[anonymous]
pswd=*
accs=readonly
root=/tmp/rrfuzz_lightftp_root
