#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
BB Trace Parser

Parses Basic Block (BB) execution traces generated by QEMU for offline static analysis.

File format:
Each BB entry contains:
- pc (uint64_t): Program counter (TB start address)
- syscall_idx (uint32_t): Associated syscall index
- flags (uint32_t): Reserved flags

Author: RR-Fuzz Team
Date: 2025-10-30
"""

import struct
import os
from typing import List, Dict, Tuple, Optional


class BBEntry:
    """Basic block execution record"""
    def __init__(self, pc: int, syscall_idx: int, flags: int = 0):
        self.pc = pc
        self.syscall_idx = syscall_idx
        self.flags = flags

    def __repr__(self):
        return f"BBEntry(pc=0x{self.pc:x}, syscall_idx={self.syscall_idx})"


class BBTraceParser:
    """BB Trace Parser"""

    ENTRY_SIZE = 16  # sizeof(rr_bb_entry_t) = 8 + 4 + 4
    # C structure definition (rr_framework.h:70-78):
    # typedef struct rr_bb_entry {
    #     uint64_t pc;
    #     uint32_t syscall_idx;
    #     uint32_t flags;
    # } rr_bb_entry_t;

    def __init__(self, bb_trace_file: str):
        self.bb_trace_file = bb_trace_file
        self.entries: List[BBEntry] = []
        self.stats = {
            'total_bbs': 0,
            'unique_pcs': 0,
            'syscalls_covered': 0
        }

    def parse(self) -> bool:
        """Parse BB trace file"""
        if not os.path.exists(self.bb_trace_file):
            print(f"Error: BB trace file not found: {self.bb_trace_file}")
            return False

        try:
            file_size = os.path.getsize(self.bb_trace_file)
            if file_size % self.ENTRY_SIZE != 0:
                print(f"Warning: file size {file_size} is not "
                      f"a multiple of entry size {self.ENTRY_SIZE}")

            with open(self.bb_trace_file, 'rb') as f:
                while True:
                    data = f.read(self.ENTRY_SIZE)
                    if len(data) < self.ENTRY_SIZE:
                        break

                    # Parse entry
                    pc, syscall_idx, flags = struct.unpack('<QII', data)
                    entry = BBEntry(pc, syscall_idx, flags)
                    self.entries.append(entry)

            # Statistics
            self.stats['total_bbs'] = len(self.entries)
            unique_pcs = set(entry.pc for entry in self.entries)
            self.stats['unique_pcs'] = len(unique_pcs)
            unique_syscalls = set(entry.syscall_idx for entry in self.entries if entry.syscall_idx > 0)
            self.stats['syscalls_covered'] = len(unique_syscalls)

            print(f"Parsed {self.stats['total_bbs']} BB entries")
            print(f"  Unique PCs:       {self.stats['unique_pcs']}")
            print(f"  Syscalls covered: {self.stats['syscalls_covered']}")

            return True

        except Exception as e:
            print(f"Error: Failed to parse BB trace: {e}")
            import traceback
            traceback.print_exc()
            return False

    def get_bb_sequence(self) -> List[int]:
        """Get BB sequence (list of PC addresses)"""
        return [entry.pc for entry in self.entries]

    def get_syscall_bb_map(self) -> Dict[int, List[int]]:
        """
        Get mapping from syscall to BBs

        Returns: {syscall_idx: [bb_pc1, bb_pc2, ...]}
        """
        syscall_bb_map = {}
        for entry in self.entries:
            if entry.syscall_idx not in syscall_bb_map:
                syscall_bb_map[entry.syscall_idx] = []
            syscall_bb_map[entry.syscall_idx].append(entry.pc)
        return syscall_bb_map

    def get_bb_between_syscalls(self, syscall_idx_start: int, syscall_idx_end: int) -> List[int]:
        """
        Get the BB sequence executed between two syscalls

        Args:
            syscall_idx_start: Start syscall index
            syscall_idx_end: End syscall index

        Returns:
            List of BB PC addresses
        """
        bb_list = []
        in_range = False

        for entry in self.entries:
            if entry.syscall_idx == syscall_idx_start:
                in_range = True

            if in_range:
                bb_list.append(entry.pc)

            if entry.syscall_idx == syscall_idx_end:
                break

        return bb_list

    def merge_with_syscall_trace(self, syscall_trace: List) -> List[Tuple[str, int]]:
        """
        Merge BB trace with syscall trace to generate a complete execution sequence

        Args:
            syscall_trace: List of syscall records (from TraceAnalyzer)

        Returns:
            Mixed sequence: [('bb', pc), ('syscall', index), ...]
        """
        merged = []
        bb_idx = 0
        current_syscall_idx = 0

        for entry in self.entries:
            # Add all BBs before the current syscall
            while bb_idx < len(self.entries) and self.entries[bb_idx].syscall_idx == current_syscall_idx:
                merged.append(('bb', self.entries[bb_idx].pc))
                bb_idx += 1

            # When syscall index changes, add the syscall
            if entry.syscall_idx > current_syscall_idx:
                merged.append(('syscall', entry.syscall_idx))
                current_syscall_idx = entry.syscall_idx

        return merged

    def get_coverage_summary(self) -> Dict[str, any]:
        """Get coverage summary"""
        return {
            'total_bbs': self.stats['total_bbs'],
            'unique_pcs': self.stats['unique_pcs'],
            'syscalls_covered': self.stats['syscalls_covered'],
            'avg_bbs_per_syscall': (self.stats['total_bbs'] / max(self.stats['syscalls_covered'], 1)
                                   if self.stats['syscalls_covered'] > 0 else 0)
        }


def main():
    """Test function"""
    import sys

    if len(sys.argv) < 2:
        print("Usage: python3 bb_trace_parser.py <trace_file.bbl>")
        sys.exit(1)

    bb_trace_file = sys.argv[1]
    parser = BBTraceParser(bb_trace_file)

    if not parser.parse():
        sys.exit(1)

    # Display statistics
    print("\n=== Coverage Summary ===")
    summary = parser.get_coverage_summary()
    for key, value in summary.items():
        print(f"  {key}: {value}")

    # Display first 10 BBs
    print("\n=== First 10 BBs ===")
    for i, entry in enumerate(parser.entries[:10]):
        print(f"  {i}: {entry}")

    # Display syscall BB mapping
    syscall_bb_map = parser.get_syscall_bb_map()
    print(f"\n=== Syscall BB Map (first 5) ===")
    for syscall_idx in sorted(syscall_bb_map.keys())[:5]:
        bbs = syscall_bb_map[syscall_idx]
        print(f"  Syscall {syscall_idx}: {len(bbs)} BBs")


if __name__ == '__main__':
    main()
